-- Part 1.
SELECT COUNT(*)
FROM manufacture_fact

-- Part 2.
SELECT TOP 10 *
FROM MATERIAL_DIM

SELECT TOP 10 *
FROM [dbo].[CALENDAR_MANUFACTURE_DIM]

SELECT TOP 10 *
FROM [dbo].[FACTORY_DIM]

SELECT TOP 10 *
FROM [dbo].[PERSON_FOREMAN_DIM]

SELECT TOP 10 *
FROM [dbo].[PRODUCT_DIM]

SELECT TOP 10 *
FROM [dbo].[PERSON_SALES_DIM]

SELECT TOP 10 *
FROM [dbo].[CALENDAR_SALES_DIM]

SELECT TOP 10 *
FROM [dbo].[PERSON_CUSTOMER_DIM]

-- Part 3.